=begin comment

Art Search API

Art Search let's you search and discover over one million pieces of historic art.

The version of the OpenAPI document: 1.0.0
Contact: mail@artsearch.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by the OpenAPI Generator
# Please update the test cases below to test the model.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;


use_ok('WWW::OpenAPIClient::Object::RetrieveArtworkById200Response');

# uncomment below and update the test
#my $instance = WWW::OpenAPIClient::Object::RetrieveArtworkById200Response->new();
#
#isa_ok($instance, 'WWW::OpenAPIClient::Object::RetrieveArtworkById200Response');


done_testing();
