/**
 * Art Search API
 * Art Search let's you search and discover over one million pieces of historic art.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mail@artsearch.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SearchArtworks200ResponseArtworksInner model module.
 * @module model/SearchArtworks200ResponseArtworksInner
 * @version 1.0.0
 */
class SearchArtworks200ResponseArtworksInner {
    /**
     * Constructs a new <code>SearchArtworks200ResponseArtworksInner</code>.
     * @alias module:model/SearchArtworks200ResponseArtworksInner
     */
    constructor() { 
        
        SearchArtworks200ResponseArtworksInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchArtworks200ResponseArtworksInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchArtworks200ResponseArtworksInner} obj Optional instance to populate.
     * @return {module:model/SearchArtworks200ResponseArtworksInner} The populated <code>SearchArtworks200ResponseArtworksInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchArtworks200ResponseArtworksInner();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchArtworks200ResponseArtworksInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchArtworks200ResponseArtworksInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['image'] && !(typeof data['image'] === 'string' || data['image'] instanceof String)) {
            throw new Error("Expected the field `image` to be a primitive type in the JSON string but got " + data['image']);
        }

        return true;
    }


}



/**
 * @member {String} title
 */
SearchArtworks200ResponseArtworksInner.prototype['title'] = undefined;

/**
 * @member {String} image
 */
SearchArtworks200ResponseArtworksInner.prototype['image'] = undefined;

/**
 * @member {Number} id
 */
SearchArtworks200ResponseArtworksInner.prototype['id'] = undefined;






export default SearchArtworks200ResponseArtworksInner;

