/*
 * Art Search API
 *
 * Art Search let's you search and discover over one million pieces of historic art.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mail@artsearch.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using artsearch.Model;
using artsearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace artsearch.Test.Model
{
    /// <summary>
    ///  Class for testing SearchArtworks200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchArtworks200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchArtworks200Response
        //private SearchArtworks200Response instance;

        public SearchArtworks200ResponseTests()
        {
            // TODO uncomment below to create an instance of SearchArtworks200Response
            //instance = new SearchArtworks200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchArtworks200Response
        /// </summary>
        [Fact]
        public void SearchArtworks200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchArtworks200Response
            //Assert.IsType<SearchArtworks200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Available'
        /// </summary>
        [Fact]
        public void AvailableTest()
        {
            // TODO unit test for the property 'Available'
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }

        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }

        /// <summary>
        /// Test the property 'Artworks'
        /// </summary>
        [Fact]
        public void ArtworksTest()
        {
            // TODO unit test for the property 'Artworks'
        }
    }
}
