/*
 * Art Search API
 *
 * Art Search let's you search and discover over one million pieces of historic art.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mail@artsearch.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using artsearch.Model;
using artsearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace artsearch.Test.Model
{
    /// <summary>
    ///  Class for testing SearchArtworks200ResponseArtworksInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchArtworks200ResponseArtworksInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchArtworks200ResponseArtworksInner
        //private SearchArtworks200ResponseArtworksInner instance;

        public SearchArtworks200ResponseArtworksInnerTests()
        {
            // TODO uncomment below to create an instance of SearchArtworks200ResponseArtworksInner
            //instance = new SearchArtworks200ResponseArtworksInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchArtworks200ResponseArtworksInner
        /// </summary>
        [Fact]
        public void SearchArtworks200ResponseArtworksInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchArtworks200ResponseArtworksInner
            //Assert.IsType<SearchArtworks200ResponseArtworksInner>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
