/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.artsearch.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.artsearch.client.model.SearchArtworks200Response
import io.artsearch.client.model.SearchArtworks200ResponseArtworksInner

class SearchArtworks200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchArtworks200Response
        //val modelInstance = SearchArtworks200Response()

        // to test the property `available`
        should("test available") {
            // uncomment below to test the property
            //modelInstance.available shouldBe ("TODO")
        }

        // to test the property `number`
        should("test number") {
            // uncomment below to test the property
            //modelInstance.number shouldBe ("TODO")
        }

        // to test the property `offset`
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

        // to test the property `artworks`
        should("test artworks") {
            // uncomment below to test the property
            //modelInstance.artworks shouldBe ("TODO")
        }

    }
}
