/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.artsearch.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.artsearch.client.model.SearchArtworks200ResponseArtworksInner

class SearchArtworks200ResponseArtworksInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchArtworks200ResponseArtworksInner
        //val modelInstance = SearchArtworks200ResponseArtworksInner()

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

    }
}
