=begin
#Art Search API

#Art Search let's you search and discover over one million pieces of historic art.

The version of the OpenAPI document: 1.0.0
Contact: mail@artsearch.io
Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/retrieve_artwork_by_id200_response'
require 'openapi_client/models/search_artworks200_response'
require 'openapi_client/models/search_artworks200_response_artworks_inner'

# APIs
require 'openapi_client/api/art_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
