{-
   Art Search API
   Art Search let's you search and discover over one million pieces of historic art.

   The version of the OpenAPI document: 1.0.0
   Contact: mail@artsearch.io

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Art exposing
    ( randomArtwork
    , retrieveArtworkById
    , searchArtworks
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode

{-| Get one random artwork from our vast collection. The API returns comprehensive details including the title, high-quality image URL, creation date range, and a rich description providing historical and artistic context.
-}
randomArtwork : Api.Request Api.Data.RetrieveArtworkById200Response
randomArtwork =
    Api.request
        "GET"
        "/artworks/random"
        []
        []
        []
        Nothing
        Api.Data.retrieveArtworkById200ResponseDecoder


{-| Get one artwork by its id. The API returns the title, image URL, start and end date, and a description of the artwork.
-}
retrieveArtworkById : Int -> Api.Request Api.Data.RetrieveArtworkById200Response
retrieveArtworkById id_path =
    Api.request
        "GET"
        "/artworks/{id}"
        [ ( "id", String.fromInt id_path ) ]
        []
        []
        Nothing
        Api.Data.retrieveArtworkById200ResponseDecoder


{-| Search and filter artworks by query, creation time, material, technique, and origin. The natural language search uses semantic AI to understand the context of your query, so you can search for artworks by their style, subject, or even emotions they evoke. The API returns a list of artworks matching the given criteria.
-}
searchArtworks : Maybe String -> Maybe Int -> Maybe Int -> Maybe Int -> Maybe Int -> Maybe Float -> Maybe Float -> Maybe String -> Maybe String -> Maybe String -> Maybe String -> Maybe Int -> Maybe Int -> Api.Request Api.Data.SearchArtworks200Response
searchArtworks query_query earliestStartDate_query latestStartDate_query earliestEndDate_query latestEndDate_query minRatio_query maxRatio_query type__query material_query technique_query origin_query offset_query number_query =
    Api.request
        "GET"
        "/artworks"
        []
        [ ( "query", Maybe.map identity query_query ), ( "earliest-start-date", Maybe.map String.fromInt earliestStartDate_query ), ( "latest-start-date", Maybe.map String.fromInt latestStartDate_query ), ( "earliest-end-date", Maybe.map String.fromInt earliestEndDate_query ), ( "latest-end-date", Maybe.map String.fromInt latestEndDate_query ), ( "min-ratio", Maybe.map String.fromFloat minRatio_query ), ( "max-ratio", Maybe.map String.fromFloat maxRatio_query ), ( "type", Maybe.map identity type__query ), ( "material", Maybe.map identity material_query ), ( "technique", Maybe.map identity technique_query ), ( "origin", Maybe.map identity origin_query ), ( "offset", Maybe.map String.fromInt offset_query ), ( "number", Maybe.map String.fromInt number_query ) ]
        []
        Nothing
        Api.Data.searchArtworks200ResponseDecoder

