=begin
#Art Search API

#Art Search let's you search and discover over one million pieces of historic art.

The version of the OpenAPI document: 1.0.0
Contact: mail@artsearch.io
Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

module OpenapiClient
  VERSION = '1.0.0'
end
