{-
   Art Search API

   Art Search let's you search and discover over one million pieces of historic art.

   OpenAPI Version: 3.0.0
   Art Search API API version: 1.0.0
   Contact: mail@artsearch.io
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : ArtSearch.API
-}

module ArtSearch.API
  ( module ArtSearch.API.Art
  ) where

import ArtSearch.API.Art