{-
   Art Search API

   Art Search let's you search and discover over one million pieces of historic art.

   OpenAPI Version: 3.0.0
   Art Search API API version: 1.0.0
   Contact: mail@artsearch.io
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : ArtSearch.Lens
-}

{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-matches -fno-warn-unused-binds -fno-warn-unused-imports #-}

module ArtSearch.ModelLens where

import qualified Data.Aeson as A
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Data, Typeable)
import qualified Data.Map as Map
import qualified Data.Set as Set
import qualified Data.Time as TI

import Data.Text (Text)

import Prelude (($), (.),(<$>),(<*>),(=<<),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

import ArtSearch.Model
import ArtSearch.Core


-- * RetrieveArtworkById200Response

-- | 'retrieveArtworkById200ResponseId' Lens
retrieveArtworkById200ResponseIdL :: Lens_' RetrieveArtworkById200Response (Maybe Int)
retrieveArtworkById200ResponseIdL f RetrieveArtworkById200Response{..} = (\retrieveArtworkById200ResponseId -> RetrieveArtworkById200Response { retrieveArtworkById200ResponseId, ..} ) <$> f retrieveArtworkById200ResponseId
{-# INLINE retrieveArtworkById200ResponseIdL #-}

-- | 'retrieveArtworkById200ResponseTitle' Lens
retrieveArtworkById200ResponseTitleL :: Lens_' RetrieveArtworkById200Response (Maybe Text)
retrieveArtworkById200ResponseTitleL f RetrieveArtworkById200Response{..} = (\retrieveArtworkById200ResponseTitle -> RetrieveArtworkById200Response { retrieveArtworkById200ResponseTitle, ..} ) <$> f retrieveArtworkById200ResponseTitle
{-# INLINE retrieveArtworkById200ResponseTitleL #-}

-- | 'retrieveArtworkById200ResponseImage' Lens
retrieveArtworkById200ResponseImageL :: Lens_' RetrieveArtworkById200Response (Maybe Text)
retrieveArtworkById200ResponseImageL f RetrieveArtworkById200Response{..} = (\retrieveArtworkById200ResponseImage -> RetrieveArtworkById200Response { retrieveArtworkById200ResponseImage, ..} ) <$> f retrieveArtworkById200ResponseImage
{-# INLINE retrieveArtworkById200ResponseImageL #-}

-- | 'retrieveArtworkById200ResponseStartDate' Lens
retrieveArtworkById200ResponseStartDateL :: Lens_' RetrieveArtworkById200Response (Maybe Int)
retrieveArtworkById200ResponseStartDateL f RetrieveArtworkById200Response{..} = (\retrieveArtworkById200ResponseStartDate -> RetrieveArtworkById200Response { retrieveArtworkById200ResponseStartDate, ..} ) <$> f retrieveArtworkById200ResponseStartDate
{-# INLINE retrieveArtworkById200ResponseStartDateL #-}

-- | 'retrieveArtworkById200ResponseEndDate' Lens
retrieveArtworkById200ResponseEndDateL :: Lens_' RetrieveArtworkById200Response (Maybe Int)
retrieveArtworkById200ResponseEndDateL f RetrieveArtworkById200Response{..} = (\retrieveArtworkById200ResponseEndDate -> RetrieveArtworkById200Response { retrieveArtworkById200ResponseEndDate, ..} ) <$> f retrieveArtworkById200ResponseEndDate
{-# INLINE retrieveArtworkById200ResponseEndDateL #-}

-- | 'retrieveArtworkById200ResponseDescription' Lens
retrieveArtworkById200ResponseDescriptionL :: Lens_' RetrieveArtworkById200Response (Maybe Text)
retrieveArtworkById200ResponseDescriptionL f RetrieveArtworkById200Response{..} = (\retrieveArtworkById200ResponseDescription -> RetrieveArtworkById200Response { retrieveArtworkById200ResponseDescription, ..} ) <$> f retrieveArtworkById200ResponseDescription
{-# INLINE retrieveArtworkById200ResponseDescriptionL #-}



-- * SearchArtworks200Response

-- | 'searchArtworks200ResponseAvailable' Lens
searchArtworks200ResponseAvailableL :: Lens_' SearchArtworks200Response (Maybe Int)
searchArtworks200ResponseAvailableL f SearchArtworks200Response{..} = (\searchArtworks200ResponseAvailable -> SearchArtworks200Response { searchArtworks200ResponseAvailable, ..} ) <$> f searchArtworks200ResponseAvailable
{-# INLINE searchArtworks200ResponseAvailableL #-}

-- | 'searchArtworks200ResponseNumber' Lens
searchArtworks200ResponseNumberL :: Lens_' SearchArtworks200Response (Maybe Int)
searchArtworks200ResponseNumberL f SearchArtworks200Response{..} = (\searchArtworks200ResponseNumber -> SearchArtworks200Response { searchArtworks200ResponseNumber, ..} ) <$> f searchArtworks200ResponseNumber
{-# INLINE searchArtworks200ResponseNumberL #-}

-- | 'searchArtworks200ResponseOffset' Lens
searchArtworks200ResponseOffsetL :: Lens_' SearchArtworks200Response (Maybe Int)
searchArtworks200ResponseOffsetL f SearchArtworks200Response{..} = (\searchArtworks200ResponseOffset -> SearchArtworks200Response { searchArtworks200ResponseOffset, ..} ) <$> f searchArtworks200ResponseOffset
{-# INLINE searchArtworks200ResponseOffsetL #-}

-- | 'searchArtworks200ResponseArtworks' Lens
searchArtworks200ResponseArtworksL :: Lens_' SearchArtworks200Response (Maybe [SearchArtworks200ResponseArtworksInner])
searchArtworks200ResponseArtworksL f SearchArtworks200Response{..} = (\searchArtworks200ResponseArtworks -> SearchArtworks200Response { searchArtworks200ResponseArtworks, ..} ) <$> f searchArtworks200ResponseArtworks
{-# INLINE searchArtworks200ResponseArtworksL #-}



-- * SearchArtworks200ResponseArtworksInner

-- | 'searchArtworks200ResponseArtworksInnerTitle' Lens
searchArtworks200ResponseArtworksInnerTitleL :: Lens_' SearchArtworks200ResponseArtworksInner (Maybe Text)
searchArtworks200ResponseArtworksInnerTitleL f SearchArtworks200ResponseArtworksInner{..} = (\searchArtworks200ResponseArtworksInnerTitle -> SearchArtworks200ResponseArtworksInner { searchArtworks200ResponseArtworksInnerTitle, ..} ) <$> f searchArtworks200ResponseArtworksInnerTitle
{-# INLINE searchArtworks200ResponseArtworksInnerTitleL #-}

-- | 'searchArtworks200ResponseArtworksInnerImage' Lens
searchArtworks200ResponseArtworksInnerImageL :: Lens_' SearchArtworks200ResponseArtworksInner (Maybe Text)
searchArtworks200ResponseArtworksInnerImageL f SearchArtworks200ResponseArtworksInner{..} = (\searchArtworks200ResponseArtworksInnerImage -> SearchArtworks200ResponseArtworksInner { searchArtworks200ResponseArtworksInnerImage, ..} ) <$> f searchArtworks200ResponseArtworksInnerImage
{-# INLINE searchArtworks200ResponseArtworksInnerImageL #-}

-- | 'searchArtworks200ResponseArtworksInnerId' Lens
searchArtworks200ResponseArtworksInnerIdL :: Lens_' SearchArtworks200ResponseArtworksInner (Maybe Int)
searchArtworks200ResponseArtworksInnerIdL f SearchArtworks200ResponseArtworksInner{..} = (\searchArtworks200ResponseArtworksInnerId -> SearchArtworks200ResponseArtworksInner { searchArtworks200ResponseArtworksInnerId, ..} ) <$> f searchArtworks200ResponseArtworksInnerId
{-# INLINE searchArtworks200ResponseArtworksInnerIdL #-}


