/**
 * Art Search API
 * Art Search let\'s you search and discover over one million pieces of historic art.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mail@artsearch.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RetrieveArtworkById200Response { 
    id?: number;
    title?: string | null;
    image?: string | null;
    start_date?: number;
    end_date?: number;
    description?: string | null;
}

