/**
 * Art Search API
 * Art Search let's you search and discover over one million pieces of historic art.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mail@artsearch.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIArtApi_H
#define OAI_OAIArtApi_H

#include "OAIHelpers.h"
#include "OAIHttpRequest.h"
#include "OAIServerConfiguration.h"
#include "OAIOauth.h"

#include "OAIRetrieveArtworkById_200_response.h"
#include "OAISearchArtworks_200_response.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPI {

class OAIArtApi : public QObject {
    Q_OBJECT

public:
    OAIArtApi(const int timeOut = 0);
    ~OAIArtApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables = QMap<QString, OAIServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);


    void randomArtwork();

    /**
    * @param[in]  id qint32 [required]
    */
    void retrieveArtworkById(const qint32 &id);

    /**
    * @param[in]  query QString [optional]
    * @param[in]  earliest_start_date qint32 [optional]
    * @param[in]  latest_start_date qint32 [optional]
    * @param[in]  earliest_end_date qint32 [optional]
    * @param[in]  latest_end_date qint32 [optional]
    * @param[in]  min_ratio double [optional]
    * @param[in]  max_ratio double [optional]
    * @param[in]  type QString [optional]
    * @param[in]  material QString [optional]
    * @param[in]  technique QString [optional]
    * @param[in]  origin QString [optional]
    * @param[in]  offset qint32 [optional]
    * @param[in]  number qint32 [optional]
    */
    void searchArtworks(const ::OpenAPI::OptionalParam<QString> &query = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<qint32> &earliest_start_date = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &latest_start_date = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &earliest_end_date = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &latest_end_date = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<double> &min_ratio = ::OpenAPI::OptionalParam<double>(), const ::OpenAPI::OptionalParam<double> &max_ratio = ::OpenAPI::OptionalParam<double>(), const ::OpenAPI::OptionalParam<QString> &type = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &material = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &technique = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &origin = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<qint32> &offset = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &number = ::OpenAPI::OptionalParam<qint32>());


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    OAIHttpRequestInput _latestInput;
    OAIHttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void randomArtworkCallback(OAIHttpRequestWorker *worker);
    void retrieveArtworkByIdCallback(OAIHttpRequestWorker *worker);
    void searchArtworksCallback(OAIHttpRequestWorker *worker);

Q_SIGNALS:

    void randomArtworkSignal(OAIRetrieveArtworkById_200_response summary);
    void retrieveArtworkByIdSignal(OAIRetrieveArtworkById_200_response summary);
    void searchArtworksSignal(OAISearchArtworks_200_response summary);

    void randomArtworkSignalFull(OAIHttpRequestWorker *worker, OAIRetrieveArtworkById_200_response summary);
    void retrieveArtworkByIdSignalFull(OAIHttpRequestWorker *worker, OAIRetrieveArtworkById_200_response summary);
    void searchArtworksSignalFull(OAIHttpRequestWorker *worker, OAISearchArtworks_200_response summary);

    Q_DECL_DEPRECATED_X("Use randomArtworkSignalError() instead")
    void randomArtworkSignalE(OAIRetrieveArtworkById_200_response summary, QNetworkReply::NetworkError error_type, QString error_str);
    void randomArtworkSignalError(OAIRetrieveArtworkById_200_response summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use retrieveArtworkByIdSignalError() instead")
    void retrieveArtworkByIdSignalE(OAIRetrieveArtworkById_200_response summary, QNetworkReply::NetworkError error_type, QString error_str);
    void retrieveArtworkByIdSignalError(OAIRetrieveArtworkById_200_response summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use searchArtworksSignalError() instead")
    void searchArtworksSignalE(OAISearchArtworks_200_response summary, QNetworkReply::NetworkError error_type, QString error_str);
    void searchArtworksSignalError(OAISearchArtworks_200_response summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    Q_DECL_DEPRECATED_X("Use randomArtworkSignalErrorFull() instead")
    void randomArtworkSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void randomArtworkSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use retrieveArtworkByIdSignalErrorFull() instead")
    void retrieveArtworkByIdSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void retrieveArtworkByIdSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use searchArtworksSignalErrorFull() instead")
    void searchArtworksSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void searchArtworksSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace OpenAPI
#endif
