# NOTE: This file is auto generated by OpenAPI Generator 7.8.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ArtSearchAPI.Model.SearchArtworks200Response do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :available,
    :number,
    :offset,
    :artworks
  ]

  @type t :: %__MODULE__{
    :available => integer() | nil,
    :number => integer() | nil,
    :offset => integer() | nil,
    :artworks => [ArtSearchAPI.Model.SearchArtworks200ResponseArtworksInner.t] | nil
  }

  alias ArtSearchAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:artworks, :list, ArtSearchAPI.Model.SearchArtworks200ResponseArtworksInner)
  end
end

