=begin
#Art Search API

#Art Search let's you search and discover over one million pieces of historic art.

The version of the OpenAPI document: 1.0.0
Contact: mail@artsearch.io
Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ArtApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ArtApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ArtApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ArtApi' do
    it 'should create an instance of ArtApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ArtApi)
    end
  end

  # unit tests for random_artwork
  # Random Artwork
  # Get one random artwork from our vast collection. The API returns comprehensive details including the title, high-quality image URL, creation date range, and a rich description providing historical and artistic context.
  # @param [Hash] opts the optional parameters
  # @return [RetrieveArtworkById200Response]
  describe 'random_artwork test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_artwork_by_id
  # Retrieve Artwork by Id
  # Get one artwork by its id. The API returns the title, image URL, start and end date, and a description of the artwork.
  # @param id The id of the artwork.
  # @param [Hash] opts the optional parameters
  # @return [RetrieveArtworkById200Response]
  describe 'retrieve_artwork_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search_artworks
  # Search Artworks
  # Search and filter artworks by query, creation time, material, technique, and origin. The natural language search uses semantic AI to understand the context of your query, so you can search for artworks by their style, subject, or even emotions they evoke. The API returns a list of artworks matching the given criteria.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :query The search query.
  # @option opts [Integer] :earliest_start_date The artwork must have been created after this date.
  # @option opts [Integer] :latest_start_date The artwork must have been created before this date.
  # @option opts [Integer] :earliest_end_date For artworks with a period of creation, the completion date must be after this date.
  # @option opts [Integer] :latest_end_date For artworks with a period of creation, the completion date must be before this date.
  # @option opts [Float] :min_ratio The minimum aspect ratio (width/height) the artwork image must have.
  # @option opts [Float] :max_ratio The maximum aspect ratio (width/height) the artwork image must have.
  # @option opts [String] :type The artwork type. Possible values are tapestry, collotype, collage, printmaking, cutting, digital_art, sculpture, metalwork, fragment, token, embroidery, painting, jewellery, print, ornament, photograph, statuette, furniture, needlework, drawing, miniature, tile, stereograph, calligraphy.
  # @option opts [String] :material The art material used. Possible values are ferrous_lactate, ink, textile, metal, bronze, canvas, stone, reduced_iron, horn, stoneware, in_shell_walnuts, chalk, velvet, silver, charcoal, gold_leaf, candied_walnuts, porcelain, walnut_halves, jade, cotton, paint, ferrous_fumarate, graphite, cobalt, sandstone, plastic, walnut_pieces, clay, walnuts, cupric_sulfate, ivory, ferric_orthophosphate, earthenware, tin, pen, linen, mahogany, electrolytic_iron, silk, crayon, black_walnuts, brush, beech_wood, terracotta, glass, lead, brass, oil_paint, pencil, leather, gold, marble, watercolor, diamond, iron, ferrous_sulfate, walnut_halves_and_pieces, gouache, wool, ceramic, parchment, cork, limestone, copper_gluconate, paper, pastel, copper, cardboard, plant_material, oak, wood.
  # @option opts [String] :technique The art technique used. Possible values are engraving, grinding, embroidering, etching, vitrification, gilding, lithography, knitting, cyanotype, silkscreen, woodcut, printing, drypoint, photolithography, weaving, sawing, casting, glassblowing, block_printing, photographing, forging.
  # @option opts [String] :origin The country or region of origin for the artwork
  # @option opts [Integer] :offset The number of artworks to skip in range [0,1000]
  # @option opts [Integer] :number The number of artworks to return in range [1,10]
  # @return [SearchArtworks200Response]
  describe 'search_artworks test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
