--[[
  Art Search API

  Art Search let's you search and discover over one million pieces of historic art.

  The version of the OpenAPI document: 1.0.0
  Contact: mail@artsearch.io
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for artsearch.model.retrieve_artwork_by_id_200_response
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("retrieve_artwork_by_id_200_response", function()
  local artsearch_retrieve_artwork_by_id_200_response = require "artsearch.model.retrieve_artwork_by_id_200_response"

  -- unit tests for the property 'id'
  describe("property id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'title'
  describe("property title test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'image'
  describe("property image test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'start_date'
  describe("property start_date test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'end_date'
  describe("property end_date test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'description'
  describe("property description test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
