--[[
  Art Search API

  Art Search let's you search and discover over one million pieces of historic art.

  The version of the OpenAPI document: 1.0.0
  Contact: mail@artsearch.io
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for artsearch.model.search_artworks_200_response
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("search_artworks_200_response", function()
  local artsearch_search_artworks_200_response = require "artsearch.model.search_artworks_200_response"

  -- unit tests for the property 'available'
  describe("property available test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'Number_'
  describe("property Number_ test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'offset'
  describe("property offset test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'artworks'
  describe("property artworks test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
