--[[
  Art Search API

  Art Search let's you search and discover over one million pieces of historic art.

  The version of the OpenAPI document: 1.0.0
  Contact: mail@artsearch.io
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for artsearch.model.search_artworks_200_response_artworks_inner
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("search_artworks_200_response_artworks_inner", function()
  local artsearch_search_artworks_200_response_artworks_inner = require "artsearch.model.search_artworks_200_response_artworks_inner"

  -- unit tests for the property 'title'
  describe("property title test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'image'
  describe("property image test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'id'
  describe("property id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
