/*
Art Search API

Art Search let's you search and discover over one million pieces of historic art.

API version: 1.0.0
Contact: mail@artsearch.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package artsearch

import (
	"encoding/json"
)

// checks if the SearchArtworks200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchArtworks200Response{}

// SearchArtworks200Response struct for SearchArtworks200Response
type SearchArtworks200Response struct {
	Available *int32 `json:"available,omitempty"`
	Number *int32 `json:"number,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
	Artworks []SearchArtworks200ResponseArtworksInner `json:"artworks,omitempty"`
}

// NewSearchArtworks200Response instantiates a new SearchArtworks200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchArtworks200Response() *SearchArtworks200Response {
	this := SearchArtworks200Response{}
	return &this
}

// NewSearchArtworks200ResponseWithDefaults instantiates a new SearchArtworks200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchArtworks200ResponseWithDefaults() *SearchArtworks200Response {
	this := SearchArtworks200Response{}
	return &this
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *SearchArtworks200Response) GetAvailable() int32 {
	if o == nil || IsNil(o.Available) {
		var ret int32
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchArtworks200Response) GetAvailableOk() (*int32, bool) {
	if o == nil || IsNil(o.Available) {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *SearchArtworks200Response) HasAvailable() bool {
	if o != nil && !IsNil(o.Available) {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given int32 and assigns it to the Available field.
func (o *SearchArtworks200Response) SetAvailable(v int32) {
	o.Available = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *SearchArtworks200Response) GetNumber() int32 {
	if o == nil || IsNil(o.Number) {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchArtworks200Response) GetNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *SearchArtworks200Response) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *SearchArtworks200Response) SetNumber(v int32) {
	o.Number = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *SearchArtworks200Response) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchArtworks200Response) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *SearchArtworks200Response) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *SearchArtworks200Response) SetOffset(v int32) {
	o.Offset = &v
}

// GetArtworks returns the Artworks field value if set, zero value otherwise.
func (o *SearchArtworks200Response) GetArtworks() []SearchArtworks200ResponseArtworksInner {
	if o == nil || IsNil(o.Artworks) {
		var ret []SearchArtworks200ResponseArtworksInner
		return ret
	}
	return o.Artworks
}

// GetArtworksOk returns a tuple with the Artworks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchArtworks200Response) GetArtworksOk() ([]SearchArtworks200ResponseArtworksInner, bool) {
	if o == nil || IsNil(o.Artworks) {
		return nil, false
	}
	return o.Artworks, true
}

// HasArtworks returns a boolean if a field has been set.
func (o *SearchArtworks200Response) HasArtworks() bool {
	if o != nil && !IsNil(o.Artworks) {
		return true
	}

	return false
}

// SetArtworks gets a reference to the given []SearchArtworks200ResponseArtworksInner and assigns it to the Artworks field.
func (o *SearchArtworks200Response) SetArtworks(v []SearchArtworks200ResponseArtworksInner) {
	o.Artworks = v
}

func (o SearchArtworks200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchArtworks200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Available) {
		toSerialize["available"] = o.Available
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Artworks) {
		toSerialize["artworks"] = o.Artworks
	}
	return toSerialize, nil
}

type NullableSearchArtworks200Response struct {
	value *SearchArtworks200Response
	isSet bool
}

func (v NullableSearchArtworks200Response) Get() *SearchArtworks200Response {
	return v.value
}

func (v *NullableSearchArtworks200Response) Set(val *SearchArtworks200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchArtworks200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchArtworks200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchArtworks200Response(val *SearchArtworks200Response) *NullableSearchArtworks200Response {
	return &NullableSearchArtworks200Response{value: val, isSet: true}
}

func (v NullableSearchArtworks200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchArtworks200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


