--[[
  Art Search API

  Art Search let's you search and discover over one million pieces of historic art.

  The version of the OpenAPI document: 1.0.0
  Contact: mail@artsearch.io
  Generated by: https://openapi-generator.tech
]]

-- search_artworks_200_response_artworks_inner class
local search_artworks_200_response_artworks_inner = {}
local search_artworks_200_response_artworks_inner_mt = {
	__name = "search_artworks_200_response_artworks_inner";
	__index = search_artworks_200_response_artworks_inner;
}

local function cast_search_artworks_200_response_artworks_inner(t)
	return setmetatable(t, search_artworks_200_response_artworks_inner_mt)
end

local function new_search_artworks_200_response_artworks_inner(title, image, id)
	return cast_search_artworks_200_response_artworks_inner({
		["title"] = title;
		["image"] = image;
		["id"] = id;
	})
end

return {
	cast = cast_search_artworks_200_response_artworks_inner;
	new = new_search_artworks_200_response_artworks_inner;
}
