--[[
  Art Search API

  Art Search let's you search and discover over one million pieces of historic art.

  The version of the OpenAPI document: 1.0.0
  Contact: mail@artsearch.io
  Generated by: https://openapi-generator.tech
]]

-- search_artworks_200_response class
local search_artworks_200_response = {}
local search_artworks_200_response_mt = {
	__name = "search_artworks_200_response";
	__index = search_artworks_200_response;
}

local function cast_search_artworks_200_response(t)
	return setmetatable(t, search_artworks_200_response_mt)
end

local function new_search_artworks_200_response(available, Number_, offset, artworks)
	return cast_search_artworks_200_response({
		["available"] = available;
		["number"] = Number_;
		["offset"] = offset;
		["artworks"] = artworks;
	})
end

return {
	cast = cast_search_artworks_200_response;
	new = new_search_artworks_200_response;
}
